#!/usr/bin/env python3
"""Regenerates the walking cat: ui/src/main/res/drawable/cat_walk_*.xml and the animation-list
ic_cat_walking.xml that plays them in order. Frame 0 has the legs straight down, so it is also the cat
standing still.

Run from the repository root:  python3 tools/make-walking-cat.py [--preview out.html]

A side-view cat built from round strokes in a 24-unit viewport: a capsule body, a round head with two
ears, a curled tail, and four straight legs that swing in diagonal pairs with their feet kept on the
ground. --preview writes an HTML page with every frame and the loop playing. Standard library only.
FRAMES and FRAME_MS are mirrored by WalkingCat.kt, which a test holds equal to ic_cat_walking.xml.
"""

import math
import pathlib
import sys

FRAMES = 8
FRAME_MS = 100
OUT = pathlib.Path("ui/src/main/res/drawable")

GROUND = 19.6
LEG = 1.7
SWING = math.radians(20)
BODY = 5.2
HIPS = (7.4, 14.2)
SHOULDERS = (14.6, 14.2)
FAR_OFFSET = 2.0     # far legs sit a little ahead, so four legs show when they line up


def fmt(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def leg(top, angle):
    # Lengthened as it swings, so the foot stays on the ground rather than lifting at each end.
    length = (GROUND - top[1]) / math.cos(angle)
    foot = (top[0] + length * math.sin(angle), GROUND)
    return f"M{fmt(top[0])},{fmt(top[1])}L{fmt(foot[0])},{fmt(foot[1])}"


def frame(t):
    swing = SWING * math.sin(2 * math.pi * t)
    far = lambda p: (p[0] + FAR_OFFSET, p[1])
    tail_tip = 3.2 + 0.6 * math.sin(2 * math.pi * t)
    return {
        "far_legs": [leg(far(HIPS), -swing), leg(far(SHOULDERS), swing)],
        "near_legs": [leg(HIPS, swing), leg(SHOULDERS, -swing)],
        "tail": f"M5.6,11.4Q2.6,11 {fmt(tail_tip)},6.4",
        "body": "M7.4,12.4L14.6,12.4",
        "head": (
            "M14.8,9.4A3,3 0 1,1 20.8,9.4A3,3 0 1,1 14.8,9.4Z"
            "M15.2,8.2L15.6,4.6L18.1,6.6Z"
            "M17.5,6.6L20,4.6L20.4,8.2Z"
        ),
    }


def vector_xml(f):
    def stroke(d, width):
        return (
            "    <path\n"
            '        android:strokeColor="@android:color/white"\n'
            f'        android:strokeWidth="{fmt(width)}"\n'
            '        android:strokeLineCap="round"\n'
            f'        android:pathData="{d}" />\n'
        )

    parts = [stroke(d, LEG) for d in f["far_legs"]]
    parts += [stroke(f["tail"], LEG), stroke(f["body"], BODY)]
    parts += [
        "    <path\n"
        '        android:fillColor="@android:color/white"\n'
        f'        android:pathData="{f["head"]}" />\n'
    ]
    parts += [stroke(d, LEG) for d in f["near_legs"]]
    return (
        "<!-- Generated by tools/make-walking-cat.py; edit the script, not this file. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24"\n'
        '    android:autoMirrored="true">\n' + "".join(parts) + "</vector>\n"
    )


def animation_xml():
    items = "".join(
        f'    <item android:drawable="@drawable/cat_walk_{i}" android:duration="{FRAME_MS}" />\n'
        for i in range(FRAMES)
    )
    return (
        "<!-- Generated by tools/make-walking-cat.py; edit the script, not this file. -->\n"
        '<animation-list xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:oneshot="false">\n' + items + "</animation-list>\n"
    )


def svg(f, size):
    def stroke(d, width):
        return f'<path d="{d}" fill="none" stroke="currentColor" stroke-width="{fmt(width)}" stroke-linecap="round"/>'

    body = "".join(stroke(d, LEG) for d in f["far_legs"])
    body += stroke(f["tail"], LEG) + stroke(f["body"], BODY)
    body += f'<path d="{f["head"]}" fill="currentColor"/>'
    body += "".join(stroke(d, LEG) for d in f["near_legs"])
    return f'<svg viewBox="0 0 24 24" width="{size}" height="{size}">{body}</svg>'


def preview(frames, out):
    total = FRAMES * FRAME_MS
    loop = lambda size: "".join(
        f'<div class="f" style="animation-delay:{i * FRAME_MS}ms">{svg(f, size)}</div>' for i, f in enumerate(frames)
    )
    pathlib.Path(out).write_text(
        "<!doctype html><meta charset=utf-8><title>Walking cat</title><style>"
        "body{font:13px sans-serif;margin:12px;background:#eee;color:#222}"
        "figure{display:inline-block;margin:3px;background:#fff}figcaption{text-align:center}"
        ".loop{position:relative;display:inline-block;margin:6px;vertical-align:middle;background:#fff}"
        f".f{{position:absolute;inset:0;opacity:0;animation:show {total}ms steps(1) infinite}}"
        f"@keyframes show{{0%{{opacity:1}}{100 / FRAMES:.3f}%{{opacity:0}}100%{{opacity:0}}}}"
        "</style>"
        + "".join(f"<figure>{svg(f, 140)}<figcaption>{i}</figcaption></figure>" for i, f in enumerate(frames))
        + "<br>"
        + "".join(f'<div class="loop" style="width:{s}px;height:{s}px">{loop(s)}</div>' for s in (96, 48, 24))
    )


def main():
    frames = [frame(i / FRAMES) for i in range(FRAMES)]
    for i, f in enumerate(frames):
        (OUT / f"cat_walk_{i}.xml").write_text(vector_xml(f))
    (OUT / "ic_cat_walking.xml").write_text(animation_xml())
    if "--preview" in sys.argv:
        preview(frames, sys.argv[sys.argv.index("--preview") + 1])


if __name__ == "__main__":
    main()
